backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: 'static/img/contents'
public_folder: '/img/contents'
collections:
  - name: 'event'
    label: 'Eventi' # Used in the UI
    folder: 'src/eventi' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - widget: string
        name: title
        label: Titolo
      - widget: string
        name: subtitle
        label: Sottotitolo
        required: false
      - widget: image
        name: image
        label: Locandina
        allow_multiple: false
      - widget: image
        name: cover
        label: Copertina (Hero)
      - widget: datetime
        name: date
        label: Data Inizio Evento
      - widget: datetime
        name: date_end
        label: Data Fine Evento
      - widget: hidden
        name: redirect_from
        required: false
      - widget: hidden
        name: permalink
        default: '/eventi/{{ page.date | dateslug }}/{{ page.fileSlug | slug }}/index.html'
      - widget: boolean
        name: published
        label: Visibile
        default: false
      - widget: boolean
        name: featured
        label: In Primo Piano (Hero)
        default: false
      - widget: object
        name: event
        label: Dettagli
        fields:
          - widget: boolean
            name: auto_meta
            label: Dettagli evento automatici
            default: false
            hint: Se attivato, bio dello speaker e dettagli dell'evento saranno generati in automatico nella pagina di dettaglio.
          - widget: string
            name: speaker
            label: Speaker
            required: false
          - widget: 'markdown'
            label: 'Biografia'
            name: 'speaker_bio'
            required: false
            buttons:
              - bold
              - italic
              - code
              - link
              - quote
              - bulleted-list
              - numbered-list
          - widget: string
            name: location
            label: Location
            default: Officina 18
            required: false
          - widget: string
            name: location_url
            label: URL Location
            default:
            required: false
          - widget: string
            name: eventbrite
            label: Codice Eventbrite
            required: false
          - widget: string
            name: youtube
            label: Link YouTube
            required: false
          - widget: string
            name: facebooklive
            label: Link Live Facebook
            required: false
          - widget: string
            name: spotifypodcast
            label: Link Episodio Podcast Spotify
            required: false
          - widget: string
            name: foto
            label: Link Foto
            required: false
          - widget: list
            name: slides
            label: Slides
            fields:
              - widget: string
                name: author
                label: Autore
                required: false
              - widget: string
                name: type
                label: 'Tipo (es: speakerdeck)'
                required: false
              - widget: string
                name: url
                label: Link
                required: false
              - widget: string
                name: id
                label: ID
                required: false
      - { label: 'Body', name: 'body', widget: 'markdown' }
